# Generated by Django 6.0.6 on 2026-06-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام کالا')),
                ('category', models.CharField(max_length=255, verbose_name='دسته بندی')),
                ('brand', models.CharField(max_length=255, verbose_name='برند')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر کالا')),
                ('stock', models.BooleanField(default=True, verbose_name='موجودی')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
                'ordering': ['-id'],
            },
        ),
    ]
